"""initialize database

Revision ID: c940fc78a5b0
Revises: 
Create Date: 2022-11-29 13:13:32.255202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c940fc78a5b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law_firms',
    sa.Column('firm_name', sa.String(length=255), nullable=False),
    sa.Column('lead', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('firm_name', 'lead')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('law_firms')
    # ### end Alembic commands ###
